#pragma once

#define ALICE_PRAGMA(x)				__pragma(x)

#define ALICE_SUPPRESS_WARNING_PUSH ALICE_PRAGMA(warning(push))

#define ALICE_SUPPRESS_WARNING_POP ALICE_PRAGMA(warning(pop))

#define ALICE_WARNING(w) ALICE_PRAGMA(warning(disable: w))

#define ALICE_SUPPRESS_WARNING	\
ALICE_WARNING(4061)				\
ALICE_WARNING(4062)				\
ALICE_WARNING(4127)				\
ALICE_WARNING(4263)				\
ALICE_WARNING(4264)				\
ALICE_WARNING(4266)				\
ALICE_WARNING(4265)				\
ALICE_WARNING(4365)				\
ALICE_WARNING(4514)				\
ALICE_WARNING(4619)				\
ALICE_WARNING(4623)				\
ALICE_WARNING(4625)				\
ALICE_WARNING(4626)				\
ALICE_WARNING(4668)				\
ALICE_WARNING(4702)				\
ALICE_WARNING(4710)				\
ALICE_WARNING(4711)				\
ALICE_WARNING(4777)				\
ALICE_WARNING(4820)				\
ALICE_WARNING(4828)				\
ALICE_WARNING(5027)				\
ALICE_WARNING(5039)				\
ALICE_WARNING(5204)				\
ALICE_WARNING(5219)				\
ALICE_WARNING(5220)				\
ALICE_WARNING(5246)				\
ALICE_WARNING(5266)				\
ALICE_WARNING(5267)

#define ALICE_SUPPRESS_WARNINGS_BEGIN	\
ALICE_SUPPRESS_WARNING_PUSH				\
ALICE_SUPPRESS_WARNING					\

#define ALICE_SUPPRESS_WARNINGS_END \
ALICE_SUPPRESS_WARNING_POP

#define ALICE_UTILITY_NAMESPACE_BEGIN	\
namespace AliceUtility					\
{										\


#define ALICE_UTILITY_NAMESPACE_END	\
}									\
